### ISSUE TITLE
How to launch google play  from app ? 

### ISSUE THREAD

**Issue by mahen23** [cartona/capacitor-google-play-availability#1]
How do i launch the google play app automatically from my app ? Suppose my app has a new version and i want users to update to the latest version. The user "taps" on the update button and they're sent directly to the google play app with my app ready to be updated.

**Comment by ramikhafagi96** [comment]
@mahen23 As described in the plugin [readme](https://github.com/cartona/capacitor-google-play-availability/blob/main/README.md) this plugin is used to check for google play services availability, what you need is [capawesome-team/[capacitor-app-update](https://github.com/capawesome-team/capacitor-app-update) which is a plugin that does exactly what you want.
